### ISSUE TITLE
Add font settings

### ISSUE THREAD

**Issue by MrHBS** [so1ve/dotfiles#1]
Do you mind adding your font settings too, like font size, line height etc.

**Comment by so1ve** [comment]
Hi @MrHBS, I'm not sure what do you mean. Do you mean my editor's font settings?

**Comment by so1ve** [comment]
Hi @MrHBS! I've just updated my config. Please check it out :)

**Comment by so1ve** [comment]
@MrHBS Sure, here it is: https://marketplace.visualstudio.com/items?itemName=so1ve.theme-undefined

It is a fork of https://marketplace.visualstudio.com/items?itemName=antfu.theme-vitesse, but with my personal preferences.
